### ISSUE TITLE
Parameters not loading properly

### ISSUE THREAD

**Issue by dvenkatsagar** [rii-mango/Papaya#48]
I have two dicom images sets, each containing like 245 images or so. I am try to load them using javascript/jquery via an ajax call. In my HTML, I have kept a select tag that selects the set and depending on the selection, I get those images and display them using the viewer. I do it like this : 

HTML :

```html
<select id="ct-set-select"> 
  <option value=null>-</option>
  <option value="set1"> Set 1</option>
  <option value="set2"> Set 1</option>
</select>
...
<div class="papaya" data-params="default_viewer"></div>
```

Javascript/Jquery : 

```javascript
var default_viewer = [];

$(document).ready(function(){
  $("#ct-set-select").on("change",function(e){
    var ct_set_select = $("#ct-set-select").find("option:selected").attr("value");
    if (ct_set_select == null){
      var params = [];
      params["images"] = [];
      params["kioskMode"] = false;
      params["showControlBar"] = true;
      papaya.Container.resetViewer(0,params);
    }else{
      $.get("/getSet",{"set_id" : ct_set_select},function(data){
        // data is a array of image file names
        var params = [];
        params["images"] = [data];
        params["kioskMode"] = true;
        params["showControlBar"] = true;
        papaya.Container.resetViewer(0,params);
      });
    }
  });
});
```

Now the problems that I am facing here are : 
- The control buttons in the control bar are not clickable, even with `kioskMode` as `false`. All are disabled for some reason.
- The image stack is not shown (trying to figure out how to show it).

Is there a better documentation on how to pass the parameters to the viewer?
Or is there a way to wipe clean the params, and start a fresh viewer.

**Comment by rii-mango** [comment]
`papaya.Container.resetViewer()` is the right way to do it.  So that looks right.

If you have other HTML elements on the page, you should put the papaya div inside another div.  See the [tests/debug_server_nested.html](https://github.com/rii-mango/Papaya/blob/master/tests/debug_server_nested.html) for an example.

```
<div class="smallViewer left">
    <div class="papaya" data-params="params1"></div>
</div>
```

I'm guessing that's the problem with the controls not working.  By default, the viewer expects to take up the full page.  When you put it in a div, it knows it's in "nested mode".  (In which case, you can set `expandable` to true, which will add a button to toggle between full screen and nested view, if you want.)  If you still can't get it working, can post a link?

> The image stack is not shown (trying to figure out how to show it).

When not in `kioskMode`, the image stack should appear at the top-right.  When `kioskMode` AND `showControlBar` are true, it will appear in the bottom right.

**Comment by dvenkatsagar** [comment]
I am keeping the `div` inside another `div`(Im using the pure-css grid system in nodejs with express), but still, the control bar buttons are disabled(I see the disabled property on them after the images are loaded, even if `kioskMode` is `true` or `false`). And also, I dont see the image stack at the bottom right even when I try keeping both the `kioskMode` and `showControlBar` to true.

Im seeing some strange behavior here, The thing is, if I keep `kioskMode` in `default_viewer` to `false` or set any parameter like this and execute the code:

```
var default_viewer = [];
default_viewer["kioskMode"] = false;
default_viewer["showControlBar"] = true
default_viewer["fullScreenPadding"] = false;
``` 

The behavior that I should expect when I select a `set` is:
- load images and show them.
- go to kioskMode.
- show the control bar with active buttons.
- the image stack should be at the bottom-right.

But what I am seeing is:
- loads images and shows them.
- goes to kioskMode.
- shows the control bar but with disabled buttons.
- the image stack shows up at the top-right corner.

When I select the null option in the select menu, it resets, but doesnt come back to the normal viewer, it still stays in kioskMode.

Another case is if I dont keep any params in the `default_viewer` and execute the code as is : 

What I should expect is to show a control bar and also go into kioskMode, but that doesnt happen, it goes into kioskMode, but doesnt show the control bar and when trying to reset it back, it stays in kioskMode.

Here is a [screenshot](http://i.imgur.com/3kro8ei.png).

**Comment by rii-mango** [comment]
There was one bug in regards to `showControlBar` and resetting.  I could recreate what you described in which the button became disabled after resetting.  That should be fixed now.  Please let me know how it works for you.

You still may have issues if you change the state of `kioskMode` or `showControlBar` when resetting.  Those are not intended to change during the life of a viewer.  But I'll see if it's possible to support that or at least a more graceful way of handing that situation.

**Comment by dvenkatsagar** [comment]
OK now the control bar buttons work. And yes, I still have issues with regard to the kioskMode not being reset. 

Is there a work around like, remove the viewer and then re-initialize it or something? I think that would be good to have. Or another approach where we can hide or show the ui components needed. 

From what I understood by looking at the source is that, even if I try to hide a ui component using jquery when resetting the viewer each time. The components dont hide(its as if, they are hard-coded with params given at the beginning). Is it by chance that, the viewer loads the images and then enforces the ui properties again? 

If so, I think a small fix for now would be to write a small feature in the source code(hack it) that triggers an event after the images are loaded and shown, and also can define that the viewer has gone the next state("ready" state or something). From there, the developer can bind that event and change the ui accordingly(he just gets notified that the viewer is ready and all the params are applied, and he can change what he wants). I think that would be good to have in the future.

I like your project by the way, Thank you.

Another question : Do we need to reapply all the settings when resetting the viewer or is it ok to just change the particular setting that is needed(I want to know if the settings are saved)?

**Comment by rii-mango** [comment]
> Is there a work around like, remove the viewer and then re-initialize it or something?

You should be able to now reset using all parameters, including `kioskMode` and `showControlBar`.   Please try again.

> From what I understood by looking at the source is that, even if I try to hide a ui component using jquery when resetting the viewer each time. The components dont hide(its as if, they are hard-coded with params given at the beginning). Is it by chance that, the viewer loads the images and then enforces the ui properties again?

Not sure.  The div IDs and CSS class names are based on src/js/constants.js.  IDs normally have an index appended to them.  Perhaps the changes I just made will resolve your issue.

> If so, I think a small fix/feature for now would be to write in the source code(hack it) that triggers an event after the images are loaded and shown, and also can define that the viewer has gone the next state("ready" state or something). From there, the developer can bind that event and change the ui accordingly(he just gets notified that the viewer is ready and all the params are applied, and he can change what he wants). I think that would be good to have in the future.

I like this idea of a ready-state callback.  I'll create a separate issue to add this in the future.

> Do we need to reapply all the settings when resetting the viewer or is it ok to just change the particular setting that is needed(I want to know if the settings are saved)?

You need to give it all the settings the second time.  It is not overwriting the old settings individually, instead it replaces the old settings object (and everything it contains) with the new one you send.  The only exception is if you don't send it any new settings -- in which case, it resets with the existing settings.

**Comment by dvenkatsagar** [comment]
Well It does go to and come back from the kioskMode now, but I get a `substr of undefined` error in the console.log. As it resets back from kioskMode(that is when select a null option in the select menu), the buttons that are hidden for the controlbar show up like [this](http://i.imgur.com/BbrJJx9.png).

**Comment by rii-mango** [comment]
Can you get a stacktrace for the error?  Also, can you let me know all the parameters you are sending (image references don't matter)?

I am testing this by creating several different sets of parameters.  Then kicking off timers which run the reset function, each time with different parameters.  At least with this simple test, I cannot recreate your error.  It toggles between different states as expected.

**Comment by dvenkatsagar** [comment]
OK i was able to fix it, the problem was the way the reset parameters are passed. I was passing an empty image parameter `params["image"] = [];` which was causing the problem. I just removed that line and now everything works fine and thank you for taking the time to fix it.

**Comment by rii-mango** [comment]
That's great!  Thanks for the feedback.
